# コード

In [14]:
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))

def identity_func(x):
    return x
def step_func(x):
    return y
def softmax_func(x):
    c=np.max(x)
    exp_x=np.exp(x-c)
    sum_exp_x=np.sum(exp_x)
    return exp_x/sum_exp_x
    
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network
def forward(network, x):
    # layer 1
    W1=network['W1']
    b1=network['b1']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    W2=network['W2']
    b2=network['b2']
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    W3=network['W3']
    b3=network['b3']
    a3=np.dot(z2,W3)+b3
    y=identity_func(a3)
    
    # layer2 layer3を実装してみてください    
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(y_batch)

[[0.31682708 0.69627909]]
[[0.31106424 0.68347634]
 [0.31457546 0.69126974]
 [0.31650383 0.69555456]
 [0.31704549 0.69676175]
 [0.3124208  0.68648478]
 [0.313803   0.68955768]
 [0.31651429 0.69556806]
 [0.31820222 0.69933468]
 [0.31579852 0.69397968]
 [0.31378849 0.68952919]
 [0.31396555 0.68991882]
 [0.31711411 0.69690637]
 [0.31232243 0.68626042]
 [0.31617197 0.69481603]
 [0.31339275 0.6886425 ]
 [0.31410117 0.69020439]]
[[0.31564642 0.69365563]
 [0.31288841 0.6875155 ]
 [0.31405883 0.69012127]
 [0.31464292 0.69141489]
 [0.31238527 0.68640627]
 [0.31709814 0.69688125]
 [0.31387688 0.68971704]
 [0.31552182 0.69336645]
 [0.31933218 0.7018466 ]
 [0.31407825 0.69017167]
 [0.31167504 0.68483669]
 [0.31595443 0.69433805]
 [0.31681108 0.69624353]
 [0.31535535 0.69300364]
 [0.31620354 0.69487697]
 [0.31511213 0.69246424]]
[[0.31557943 0.69349326]
 [0.31516539 0.69257806]
 [0.3132064  0.68822815]
 [0.31479741 0.69176431]
 [0.3180727  0.69904358]
 [0.31466543 0.69147633]
 [0.3115177  0.6844871

# 感想
* 数式を繋いでやっていくことでニューラルネットワークが構築出来ることが分かった
* 計算式を読み解くことがちゃんとできていないので頑張りたい

# 参考文献
* http://www.kamishima.net/mlmpyja/lr/sigmoid.html